// Content for the party games: spyfall locations, codenames words, fill-in-the-blank prompts, heist jobs.

// [name, emoji, roles]
const SPY_LOCATIONS = [
  ['Airplane', '✈️', ['Pilot', 'Flight attendant', 'Air marshal', 'First-class passenger', 'Crying baby’s parent', 'Mechanic', 'Co-pilot']],
  ['Bank', '🏦', ['Teller', 'Manager', 'Security guard', 'Robber', 'Customer', 'Loan officer', 'Armored truck driver']],
  ['Beach', '🏖️', ['Lifeguard', 'Surfer', 'Ice cream seller', 'Tourist', 'Kid building sandcastles', 'Photographer', 'Beach volleyball player']],
  ['Casino', '🎰', ['Dealer', 'High roller', 'Bouncer', 'Bartender', 'Card counter', 'Pit boss', 'Lucky grandma']],
  ['Circus', '🎪', ['Clown', 'Acrobat', 'Lion tamer', 'Ringmaster', 'Juggler', 'Visitor', 'Magician']],
  ['Hospital', '🏥', ['Nurse', 'Surgeon', 'Patient', 'Intern', 'Therapist', 'Visitor', 'Janitor']],
  ['Hotel', '🏨', ['Receptionist', 'Bellhop', 'Guest', 'Housekeeper', 'Manager', 'Room-service chef', 'Doorman']],
  ['Movie studio', '🎬', ['Director', 'Stuntman', 'Actor', 'Camera operator', 'Costume designer', 'Extra', 'Sound engineer']],
  ['Pirate ship', '🏴‍☠️', ['Captain', 'Cook', 'Prisoner', 'Cabin boy', 'Navigator', 'Gunner', 'Parrot keeper']],
  ['Police station', '🚓', ['Detective', 'Lawyer', 'Journalist', 'Criminal', 'Desk sergeant', 'Forensic scientist', 'Rookie cop']],
  ['Restaurant', '🍝', ['Chef', 'Waiter', 'Food critic', 'Dishwasher', 'Customer', 'Host', 'Sommelier']],
  ['School', '🏫', ['Teacher', 'Student', 'Principal', 'Janitor', 'Lunch lady', 'Gym coach', 'Substitute teacher']],
  ['Space station', '🛰️', ['Commander', 'Engineer', 'Scientist', 'Space tourist', 'Doctor', 'Alien (probably)', 'Pilot']],
  ['Submarine', '🌊', ['Captain', 'Sonar operator', 'Cook', 'Navigator', 'Engineer', 'Torpedo officer', 'Radio operator']],
  ['Supermarket', '🛒', ['Cashier', 'Shelf stocker', 'Butcher', 'Customer', 'Manager', 'Security guard', 'Free-sample lady']],
  ['Theater', '🎭', ['Actor', 'Prompter', 'Usher', 'Critic', 'Audience member', 'Stagehand', 'Costume maker']],
  ['University', '🎓', ['Professor', 'Student', 'Dean', 'Librarian', 'Researcher', 'Exchange student', 'Campus security']],
  ['Zoo', '🦁', ['Zookeeper', 'Vet', 'Tourist', 'Kid on a field trip', 'Photographer', 'Researcher', 'Snack vendor']],
  ['Military base', '🪖', ['General', 'Sergeant', 'Medic', 'Sniper', 'Cook', 'Deserter', 'Radio operator']],
  ['Night club', '🪩', ['DJ', 'Bouncer', 'Bartender', 'Dancer', 'VIP', 'Bachelor party', 'Coat check']],
  ['Wedding', '💒', ['Bride', 'Groom', 'Best man', 'Flower girl', 'Officiant', 'Photographer', 'Uninvited ex']],
  ['Haunted house', '👻', ['Ghost hunter', 'Medium', 'Skeptic', 'Caretaker', 'Teenager on a dare', 'Realtor', 'Ghost (allegedly)']],
  ['Gaming convention', '🎮', ['Pro gamer', 'Cosplayer', 'Streamer', 'Developer', 'Merch seller', 'Fan', 'Security']],
  ['Ski resort', '⛷️', ['Ski instructor', 'Snowboarder', 'Lift operator', 'Medic', 'Tourist', 'Hot cocoa vendor', 'Ski patrol']],
];

const CODENAMES_WORDS = [
  'Africa', 'Agent', 'Air', 'Alien', 'Alps', 'Amazon', 'Ambulance', 'America', 'Angel', 'Antarctica', 'Apple', 'Arm', 'Atlantis',
  'Australia', 'Aztec', 'Back', 'Ball', 'Band', 'Bank', 'Bar', 'Bark', 'Bat', 'Battery', 'Beach', 'Bear', 'Beat', 'Bed', 'Beijing',
  'Bell', 'Belt', 'Berlin', 'Bermuda', 'Berry', 'Bill', 'Block', 'Board', 'Bolt', 'Bomb', 'Bond', 'Boom', 'Boot', 'Bottle', 'Bow',
  'Box', 'Bridge', 'Brush', 'Buck', 'Buffalo', 'Bug', 'Bugle', 'Button', 'Calf', 'Canada', 'Cap', 'Capital', 'Car', 'Card',
  'Carrot', 'Casino', 'Cast', 'Cat', 'Cell', 'Centaur', 'Center', 'Chair', 'Change', 'Charge', 'Check', 'Chest', 'Chick', 'China',
  'Chocolate', 'Church', 'Circle', 'Cliff', 'Cloak', 'Club', 'Code', 'Cold', 'Comic', 'Compound', 'Concert', 'Conductor', 'Contract',
  'Cook', 'Copper', 'Cotton', 'Court', 'Cover', 'Crane', 'Crash', 'Cricket', 'Cross', 'Crown', 'Cycle', 'Czech', 'Dance', 'Date',
  'Day', 'Death', 'Deck', 'Degree', 'Diamond', 'Dice', 'Dinosaur', 'Disease', 'Doctor', 'Dog', 'Draft', 'Dragon', 'Dress', 'Drill',
  'Drop', 'Duck', 'Dwarf', 'Eagle', 'Egypt', 'Embassy', 'Engine', 'England', 'Europe', 'Eye', 'Face', 'Fair', 'Fall', 'Fan',
  'Fence', 'Field', 'Fighter', 'Figure', 'File', 'Film', 'Fire', 'Fish', 'Flute', 'Fly', 'Foot', 'Force', 'Forest', 'Fork',
  'France', 'Game', 'Gas', 'Genius', 'Germany', 'Ghost', 'Giant', 'Glass', 'Glove', 'Gold', 'Grace', 'Grass', 'Greece', 'Green',
  'Ground', 'Ham', 'Hand', 'Hawk', 'Head', 'Heart', 'Helicopter', 'Himalayas', 'Hole', 'Hollywood', 'Honey', 'Hood', 'Hook',
  'Horn', 'Horse', 'Hospital', 'Hotel', 'Ice', 'Ice cream', 'India', 'Iron', 'Ivory', 'Jack', 'Jam', 'Jet', 'Jupiter', 'Kangaroo',
  'Ketchup', 'Key', 'Kid', 'King', 'Kiwi', 'Knife', 'Knight', 'Lab', 'Lap', 'Laser', 'Lawyer', 'Lead', 'Lemon', 'Leprechaun',
  'Life', 'Light', 'Limousine', 'Line', 'Link', 'Lion', 'Litter', 'Loch Ness', 'Lock', 'Log', 'London', 'Luck', 'Mail', 'Mammoth',
  'Maple', 'Marble', 'March', 'Mass', 'Match', 'Mercury', 'Mexico', 'Microscope', 'Millionaire', 'Mine', 'Mint', 'Missile', 'Model',
  'Mole', 'Moon', 'Moscow', 'Mount', 'Mouse', 'Mouth', 'Mug', 'Nail', 'Needle', 'Net', 'New York', 'Night', 'Ninja', 'Note',
  'Novel', 'Nurse', 'Nut', 'Octopus', 'Oil', 'Olive', 'Olympus', 'Opera', 'Orange', 'Organ', 'Palm', 'Pan', 'Pants', 'Paper',
  'Parachute', 'Park', 'Part', 'Pass', 'Paste', 'Penguin', 'Phoenix', 'Piano', 'Pie', 'Pilot', 'Pin', 'Pipe', 'Pirate', 'Pistol',
  'Pit', 'Pitch', 'Plane', 'Plastic', 'Plate', 'Platypus', 'Play', 'Plot', 'Point', 'Poison', 'Pole', 'Police', 'Pool', 'Port',
  'Post', 'Pound', 'Press', 'Princess', 'Pumpkin', 'Pupil', 'Pyramid', 'Queen', 'Rabbit', 'Racket', 'Ray', 'Revolution', 'Ring',
  'Robin', 'Robot', 'Rock', 'Rome', 'Root', 'Rose', 'Roulette', 'Round', 'Row', 'Ruler', 'Satellite', 'Saturn', 'Scale', 'School',
  'Scientist', 'Scorpion', 'Screen', 'Scuba diver', 'Seal', 'Server', 'Shadow', 'Shakespeare', 'Shark', 'Ship', 'Shoe', 'Shop',
  'Shot', 'Sink', 'Skyscraper', 'Slip', 'Slug', 'Smuggler', 'Snow', 'Snowman', 'Sock', 'Soldier', 'Soul', 'Sound', 'Space',
  'Spell', 'Spider', 'Spike', 'Spine', 'Spot', 'Spring', 'Spy', 'Square', 'Stadium', 'Staff', 'Star', 'State', 'Stick', 'Stock',
  'Straw', 'Stream', 'Strike', 'String', 'Sub', 'Suit', 'Superhero', 'Swing', 'Switch', 'Table', 'Tablet', 'Tag', 'Tail', 'Tap',
  'Teacher', 'Telescope', 'Temple', 'Theater', 'Thief', 'Thumb', 'Tick', 'Tie', 'Time', 'Tokyo', 'Tooth', 'Torch', 'Tower',
  'Track', 'Train', 'Triangle', 'Trip', 'Trunk', 'Tube', 'Turkey', 'Undertaker', 'Unicorn', 'Vacuum', 'Van', 'Vet', 'Wake',
  'Wall', 'War', 'Washer', 'Washington', 'Watch', 'Water', 'Wave', 'Web', 'Well', 'Whale', 'Whip', 'Wind', 'Witch', 'Worm', 'Yard',
];

// "____" marks the blank.
const BLANK_PROMPTS = [
  'The worst thing to hear your pilot say: “____”',
  'A rejected flavor of Doritos: ____',
  'The real reason the dinosaurs went extinct: ____',
  'What’s actually at the bottom of the Mariana Trench? ____',
  'The worst possible name for a boat: ____',
  'A terrible thing to put on a wedding cake: ____',
  'What your pet says about you when you’re not home: “____”',
  'The worst superpower: ____',
  'A bad slogan for a funeral home: “____”',
  'The 11th commandment: “Thou shalt not ____”',
  'The first thing aliens would complain about on Earth: ____',
  'A rejected Olympic sport: ____',
  'The title of my autobiography: “____”',
  'The worst thing to find in your Happy Meal: ____',
  'What Gordon Ramsay yells at his own kids: “____”',
  'The worst thing to say on a first date: “____”',
  'A new holiday nobody asked for: ____ Day',
  'The secret ingredient in grandma’s cookies: ____',
  'The worst thing to name your WiFi: “____”',
  'What really happens in the Bermuda Triangle: ____',
  'An unexpected thing to see at a gym: ____',
  'A terrible fortune-cookie fortune: “____”',
  'Something you should never microwave: ____',
  'The least intimidating gang name: The ____',
  'A rejected Disney princess: Princess ____',
  'What the group chat would be called if it were a band: ____',
  'The worst way to start a eulogy: “____”',
  'A horrible thing to whisper in someone’s ear at a party: “____”',
  'The worst prize at the bottom of a cereal box: ____',
  'The real reason the Mona Lisa is smiling: ____',
  'The worst thing your GPS could say: “____”',
  'A weird thing to collect: ____',
  'What’s really in the Area 51 vending machine: ____',
  'Rejected name for a new energy drink: ____',
  'A bad thing to hear from your dentist: “____”',
  'The most useless college degree: a major in ____',
  'The worst thing to bring to a potluck: ____',
  'What pirates actually buried: ____',
  'A very specific phobia: fear of ____',
  'The last text you’d want to get from your mom: “____”',
  'A rejected Pokémon: ____',
  'The worst theme for a kid’s birthday party: ____',
  'What the 8-ball says when it’s had enough: “____”',
  'The worst thing a magician could pull out of a hat: ____',
  'A crime that should exist: ____',
  'The next big social media app: ____',
];

// Heist targets and the obstacles along the way. Each option: [label, success chance, extra loot multiplier].
const HEIST_TARGETS = [
  { name: 'First National Bank', emoji: '🏦' },
  { name: 'the Museum of Fine Art', emoji: '🖼️' },
  { name: 'the Golden Palms Casino', emoji: '🎰' },
  { name: 'a billionaire’s yacht', emoji: '🛥️' },
  { name: 'the crypto exchange’s cold wallet', emoji: '💾' },
  { name: 'the royal jewel vault', emoji: '👑' },
];
const HEIST_STAGES = [
  { text: '🚨 A guard is patrolling the loading dock.', options: [['Sneak past in the shadows', 0.7, 0.3], ['Bribe him with a sandwich', 0.85, 0.15], ['Knock him out', 0.55, 0.5]] },
  { text: '🔐 A keypad lock blocks the vault corridor.', options: [['Brute-force the code', 0.6, 0.45], ['Use the stolen keycard', 0.8, 0.2], ['Blow the door', 0.5, 0.6]] },
  { text: '📹 Security cameras cover the main hall.', options: [['Loop the footage', 0.7, 0.3], ['Spray paint the lenses', 0.8, 0.2], ['Cut the power to the whole block', 0.5, 0.55]] },
  { text: '🐕 A guard dog is sleeping by the stairs.', options: [['Tiptoe past', 0.65, 0.35], ['Throw it a steak', 0.85, 0.15], ['Pet it (bold)', 0.45, 0.6]] },
  { text: '🔦 Laser grid in the gallery.', options: [['Dance through it', 0.55, 0.5], ['Mirrors to reflect the beams', 0.75, 0.3], ['Go around through the vents', 0.85, 0.1]] },
  { text: '🚓 Sirens! A patrol car pulls up outside.', options: [['Hide and wait', 0.75, 0.2], ['Create a distraction', 0.65, 0.35], ['Floor it out the back', 0.5, 0.55]] },
  { text: '🧑‍💼 The night manager is working late.', options: [['Pose as the cleaning crew', 0.75, 0.25], ['Lock him in his office', 0.6, 0.4], ['Recruit him (cut him in)', 0.85, 0.05]] },
  { text: '🧨 The safe has a time lock.', options: [['Crack it by ear', 0.6, 0.45], ['Drill the hinges', 0.75, 0.3], ['Take the whole safe', 0.45, 0.7]] },
];

module.exports = { SPY_LOCATIONS, CODENAMES_WORDS, BLANK_PROMPTS, HEIST_TARGETS, HEIST_STAGES };
